"""`tcl` rule: runs an existing Tcl script with a tool's Tcl interpreter (tclsh or an EDA shell).

`command: [<tool>, <script>, args…]` becomes `<tool> .ebs/ebs_main.tcl args…`. The generated
wrapper sources `.ebs/ebs_params.tcl` (the step params as `::ebs(name)`), then the user script
with `::argv0` set to it, so `$argv`, `$argv0` and `[info script]` look as if it ran directly.

Generated files are pure ASCII: every value is quoted for Tcl by `tcl_quote`, which uses braces
when that is exact and backslash escapes otherwise, so the result does not depend on the tool's
system encoding. Tcl 8.6+ is needed; characters outside the BMP (`\\U` escapes) need
Tcl 8.6.10+ or 9.
"""

from __future__ import annotations

from collections.abc import Mapping

from ebs.core.errors import RuleError
from ebs.flow.interp import ParamValue
from ebs.flow.model import StepDef
from ebs.rules.api import (
    GENERATED_DIR,
    ActionTemplate,
    BaseRule,
    ExpandContext,
    param_text,
    render_command,
)

__all__ = ["MAIN_PATH", "PARAMS_PATH", "TclRule", "main_file", "params_file", "tcl_quote"]

PARAMS_PATH = f"{GENERATED_DIR}/ebs_params.tcl"
MAIN_PATH = f"{GENERATED_DIR}/ebs_main.tcl"

_PRINTABLE = frozenset(chr(c) for c in range(0x20, 0x7F))
_BARE = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")


def _brace_safe(value: str) -> bool:
    # Inside braces nothing is substituted except backslash-newline, so: printable ASCII only,
    # no backslash at all, and braces balanced so the word ends at the final `}`.
    depth = 0
    for ch in value:
        if ch not in _PRINTABLE or ch == "\\":
            return False
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


def _escape(ch: str) -> str:
    if ch in _BARE:
        return ch  # letters and digits: a backslash before them would mean \n, \t, \0…
    code = ord(ch)
    if ch in _PRINTABLE:
        return "\\" + ch  # `\X` is X for punctuation and space
    if code <= 0xFFFF:
        return f"\\u{code:04x}"  # exactly 4 digits, so a following hex digit is not consumed
    return f"\\U{code:08x}"


def tcl_quote(value: str) -> str:
    """Quote `value` as one Tcl word that evaluates to exactly `value`."""
    if _brace_safe(value):
        return "{" + value + "}"
    return "".join(_escape(ch) for ch in value)


def _tcl_value(value: ParamValue) -> str:
    if isinstance(value, tuple):  # a proper Tcl list, one quoted word per element
        return tcl_quote(" ".join(tcl_quote(item) for item in value))
    return tcl_quote(param_text(value))


def params_file(params: Mapping[str, ParamValue]) -> str:
    """`set ::ebs(name) {value}` per param, sorted by name; lists become Tcl lists."""
    lines = [
        "# Generated by ebs (rule tcl): step params as ::ebs(name). Do not edit.",
        "array set ::ebs {}",
    ]
    lines += [f"set ::ebs({name}) {_tcl_value(params[name])}" for name in sorted(params)]
    return "\n".join(lines) + "\n"


def main_file(script: str) -> str:
    return (
        "# Generated by ebs (rule tcl): params, then the step's script. Do not edit.\n"
        f"source {PARAMS_PATH}\n"
        f"set ::argv0 {tcl_quote(script)}\n"
        f"source {tcl_quote(script)}\n"
    )


class TclRule(BaseRule):
    kind = "tcl"
    version = "1"

    def validate(self, step: StepDef) -> None:
        if step.script is not None:
            raise RuleError(
                "a 'tcl' step does not take 'script': give the tool and the script file as "
                "'command: [<tclsh-or-tool>, <script.tcl>, args…]'"
            )
        if step.command is None:
            raise RuleError(
                "a 'tcl' step's 'command' is required: [<tclsh-or-tool>, <script.tcl>, args…]"
            )
        if len(step.command) < 2:
            raise RuleError(
                "a 'tcl' step's 'command' needs a tool and a script: "
                "[<tclsh-or-tool>, <script.tcl>, args…]"
            )
        self._reject_fields(
            step, ("workdir", "target"), "only 'make' steps use 'workdir' and 'target'"
        )

    def expand(self, step: StepDef, ctx: ExpandContext) -> ActionTemplate:
        self.validate(step)
        assert step.command is not None
        tool = ctx.render_str(step.command[0], field="command[0]")
        script = ctx.render_str(step.command[1], field="command[1]")
        args = render_command(step.command[2:], ctx, start=2)
        return ActionTemplate(
            argv=(tool, MAIN_PATH, *args),
            env=dict(ctx.instance.env),
            config_files={
                PARAMS_PATH: params_file(ctx.instance.params),
                MAIN_PATH: main_file(script),
            },
        )
